version: "3.3"

services:
  bot:
    build: .
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - wiki_network

networks:
  wiki_network:
    external:
      name: wiki_mediawiki

